# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >-
  Rugenerous Improvement Proposals (RIPs) describe standards for the Rugenerous
  platform, including core protocol specifications, client APIs, and contract
  standards.
url: "https://rips.rug.farm"
repository: rugenerous/RIPS
twitter_username: iearnfinance
github_username: rugenerous
header_pages:
  - all-rip.html
twitter:
  card: summary
  username: iearnfinance

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

permalink: /:slug

defaults:
  - scope:
      path: "RIPS"
    values:
      layout: "rip"
  - scope:
      path: ""
    values:
      image: "/assets/og_image.png"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - rip-X.md
